# Generated by Django 2.1.3 on 2018-11-19 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_your_csv_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='your_csv',
            name='your_csv',
            field=models.FileField(upload_to=''),
        ),
    ]
