# Generated by Django 2.1.3 on 2018-11-19 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_auto_20181118_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='your_csv',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
